controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# перенаправление домашней страницы
homepage:
    path: /
    controller: App\Controller\SalaryController::index
    defaults:
        path: /salary
        permanent: true
